ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "headline" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "canHelp" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "lookingFor" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "BusinessProfile" ADD COLUMN IF NOT EXISTS "headline" TEXT;
ALTER TABLE "BusinessProfile" ADD COLUMN IF NOT EXISTS "canHelp" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "BusinessProfile" ADD COLUMN IF NOT EXISTS "lookingFor" TEXT[] DEFAULT ARRAY[]::TEXT[];
